name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagget-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Build"
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r ./requirements.txt
          python3 -m pip install pyinstaller
          pyinstaller -F -n vpnm --clean vpnm/app.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN}}"
          prerelease: false
          files: |
            ./dist/vpnm