name: "latest-release"

on:
  push:
    branches:
      - "main"

jobs:
  tagget-release:
    name: "Latest Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: "Set up python3.9"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install dependencies"
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          poetry export -f requirements.txt --output requirements.txt
          pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pip install pylint
          pylint --max-line-length=88 --disable=C0115,C0114,C0116,W0107,R0914 --notes= vpnm/
      - name: "Build"
        run: |
          pip install pyinstaller
          pyinstaller -F -n vpnm --clean vpnm/app.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest build"
          files: |
            dist/vpnm