name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagget-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    environment: "build"

    steps:
      - uses: actions/checkout@v2
      - name: "Set up python3.9"
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install dependencies"
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry
          poetry export -o requirements.txt --without-hashes
          pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pip install pylint
          pylint --max-line-length=88 --disable=missing-function-docstring,too-many-branches,unspecified-encoding --notes= vpnm/ app.py
      - name: "Build"
        env:
          VPNM_API_URL: ${{ secrets.VPNM_API_URL }}
        run: |
          echo ${{ VPNM_API_URL }}
          pip install pyinstaller
          pyinstaller -F -n vpnm --clean app.py
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Latest build"
          files: |
            dist/vpnm
